# -*- coding: utf-8 -*-
"""Task 1: Reddit_Twitter_Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfB5mOZn973IEBLNcBC7f5WttnGUTD3N

#**Choice 3: Reddit & Twitter Topic Research Bot**
"""

!pip install praw tweepy gspread oauth2client

import praw
import tweepy

#Reddit Setup
reddit = praw.Reddit(
    client_id="3ZC1I0FifnOeQS1k63P0Ig",
    client_secret="Opyc_FWOnjuP3qSiLAcVuAlXsi58ig",
    user_agent="reddit-search-bot"
)

#Twitter Setup
bearer_token = "AAAAAAAAAAAAAAAAAAAAACI70QEAAAAAdg4%2BLdjo5hPOvCSdWUE1Tgq%2BnFc%3DMTG5oqOegsjfkakxlCiJ5F9ujIWVIhS5DvyyK1dN5ruLb5iT6g"
client = tweepy.Client(bearer_token=bearer_token)

#user Input
query = input("Enter a topic: ")

#Reddit Search
reddit_results = []
for post in reddit.subreddit("all").search(query, limit=5):
    reddit_results.append({
        "title": post.title,
        "url": post.url,
        "comments": post.num_comments
    })

#Twitter Search
twitter_results = []
try:
    response = client.search_recent_tweets(query=query, max_results=10)
    if response.data:
        for tweet in response.data:
            twitter_results.append({
                "title": tweet.text,
                "url": f"https://twitter.com/i/web/status/{tweet.id}",
                "comments": "N/A"
            })
except tweepy.TooManyRequests:
    print("⏳ Rate limit hit. Please wait 15 minutes before retrying.")


all_results = reddit_results + twitter_results

print("\n--- Combined Reddit + Twitter Results ---")
for r in all_results:
    print(f"\nTitle: {r['title']}\nURL: {r['url']}\nComments: {r['comments']}")

import gspread
from oauth2client.service_account import ServiceAccountCredentials

# Define scope and authorize credentials
scope = ["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
creds = ServiceAccountCredentials.from_json_keyfile_name("credentials.json", scope)
client = gspread.authorize(creds)

# Open the sheet
sheet = client.open("Reddit_Twitter_Research").sheet1

# Clear existing data
sheet.clear()

# Set headers
sheet.append_row(["Platform", "Title", "URL", "Comments"])

#  Add Reddit results (variable name: results)
for r in reddit_results:
    sheet.append_row(["Reddit", r['title'], r['url'], r['comments']])

# Add Twitter results
for t in twitter_results:
    sheet.append_row(["Twitter", t['title'], t['url'], t['comments']])

print("Data successfully written to Google Sheets!")

